# -----------------------------------------------------------------------------
# pqse_gowin.tcl - PQSE secure element on the Tang Nano 20K (GW2AR-18) with the
# vendor flow: GowinSynthesis + Gowin place & route, area-oriented settings.
#
#   gw_sh gowin/pqse_gowin.tcl                       (from the repository root)
#   PUF=1 MASKED=0 gw_sh gowin/pqse_gowin.tcl        (options as environment
#                                                     variables)
#
#   PUF     bfly (default here; make se-gowin-eda passes its own PUF, default 1):
#           butterfly-cell PUF (2 latches per bit, no LUTs)
#           1: cross-coupled NAND PUF (2 LUTs per bit); 0: simulation PUF model
#   MASKED  1 (default) or 0 (the unprotected reference build)
#   MAP     GowinSynthesis LUT mapping (-map_option): 1 (default mapping) or 2
#           (LUT5-oriented without more LUTs); 3 / 4 trade LUTs for timing
#   STEP    all (default: synthesis + place & route, the real fit) or syn
#   FREQ    clock constraint in MHz, 27 (default: the Tang Nano 20K's oscillator,
#           no PLL needed; the design is a contactless-card core, 13.56 MHz on
#           silicon). At 50 MHz the first fit missed timing (Fmax ~37 MHz: the
#           instruction decode into the RAM read addresses, 18 logic levels)
#   DEVICE  20k (default: Tang Nano 20K, GW2AR-LV18QN88C8/I7) or 9k (Tang Nano 9K,
#           GW1NR-LV9QN88PC6/I5); both boards have a 27 MHz oscillator. 9k builds
#           go to build/gowin/m<MASKED>_p<PUF>_9k/
#   PLACE   place & route effort: -place_option (0 default; 1, 2: more effort,
#   ROUTE   better at congested fits) / -route_option (0 default; 1, 2); unset:
#           the tool's defaults. For a nearly full 9K: PLACE=1 ROUTE=1 (or 2)
#   TOP     synthesize one hw/se module alone instead of the whole design
#           (diagnosis: make se-gowin-bisect runs every module with STEP=syn
#           and counts GowinSynthesis errors per module); build/gowin/bisect/<TOP>/
#
# The same build as "make se-gowin" (PQSE_LUTRAM_1R, the selected PUF), so the
# two counts compare directly. gw_sh has no option for Verilog defines or top
# parameters, so the script writes one wrapper file: the defines, an `include
# of every hw/se source, and a top pqse_gowin_top that sets MASKED.
# No pin constraints: place & route places the 9 pins itself (a fit estimate,
# not a board build). Without a display, gw_sh prints a Qt / OpenGL warning
# ("Cannot create platform OpenGL context"): harmless; QT_QPA_PLATFORM=offscreen
# silences it.
#
# Results in build/gowin/m<MASKED>_p<PUF>/pqse/impl/ (create_project makes the
# pqse/ project directory):
#   gwsynthesis/pqse_syn.rpt.html   synthesis resource report
#   pnr/pqse.rpt.txt / .rpt.html    the fit after place & route ("Resource
#                                   Usage Summary": Logic = LUT + ALU + SSRAM,
#                                   Register, BSRAM, DSP), the number to trust
# -----------------------------------------------------------------------------
proc env_or {name default} {
  if {[info exists ::env($name)] && $::env($name) ne ""} { return $::env($name) }
  return $default
}
set PUF    [env_or PUF bfly]
set MASKED [env_or MASKED 1]
set MAP    [env_or MAP 1]
set STEP   [env_or STEP all]
set TOP    [env_or TOP pqse_gowin_top]
set FREQ   [env_or FREQ 27]
set DEVICE [env_or DEVICE 20k]
set PLACE  [env_or PLACE ""]
set ROUTE  [env_or ROUTE ""]

set root [file normalize [file join [file dirname [info script]] ..]]
switch -- $DEVICE {
  20k     { set PART GW2AR-LV18QN88C8/I7; set DSUF "" }
  9k      { set PART GW1NR-LV9QN88PC6/I5; set DSUF "_9k" }
  default { error "DEVICE must be 20k or 9k (got $DEVICE)" }
}
set out  [file join $root build gowin m${MASKED}_p${PUF}${DSUF}]
if {$TOP ne "pqse_gowin_top"} { set out [file join $root build gowin bisect $TOP] }
file mkdir $out

# ---- wrapper: defines, sources, top with the MASKED parameter ----
set src [file join $out pqse_gowin_all.v]
set fh  [open $src w]
puts $fh "// generated by gowin/pqse_gowin.tcl - do not edit"
puts $fh "`define PQSE_GOWIN_EDA"
puts $fh "`define PQSE_LUTRAM_1R"
switch -- $PUF {
  1       { puts $fh "`define PQSE_PUF_LATCH" }
  bfly    { puts $fh "`define PQSE_PUF_BFLY" }
  0       { }
  default { error "PUF must be bfly, 1 or 0 (got $PUF)" }
}
foreach f [lsort [glob [file join $root hw se *.v]]] {
  puts $fh "`include \"$f\""
}
puts $fh {
module pqse_gowin_top (
  input  wire clk,
  input  wire rst_n,
  input  wire spi_sck,
  input  wire spi_cs_n,
  input  wire spi_mosi,
  output wire spi_miso,
  output wire irq,
  input  wire tamper,
  output wire trig
);}
puts $fh "  pqse_top #(.MASKED($MASKED)) u_top ("
puts $fh {    .clk(clk), .rst_n(rst_n), .spi_sck(spi_sck), .spi_cs_n(spi_cs_n),
    .spi_mosi(spi_mosi), .spi_miso(spi_miso), .irq(irq), .tamper(tamper), .trig(trig));
endmodule}
close $fh

# tuning options: not every gw_sh version knows every option (or value), so an
# unknown one is reported and skipped instead of stopping the build
# (GowinSynthesis is the default synthesis tool: no -synthesis_tool needed)
proc try_option {args} {
  if {[catch {set_option {*}$args} msg]} {
    puts "pqse_gowin.tcl: skipped 'set_option $args' ($msg)"
  }
}
# ---- clock constraint (an SDC file; without one the timing report only
# uses -global_freq) ----
set sdc [file join $out pqse.sdc]
set fh  [open $sdc w]
set per [format %.3f [expr {1000.0 / $FREQ}]]
set hp  [format %.3f [expr {500.0 / $FREQ}]]
puts $fh "create_clock -name clk -period $per -waveform {0 $hp} \[get_ports {clk}\]"
# butterfly PUF: the 32 column gate nets drive the latch gate pins (clock pins
# to the timing analyser, TA1132 "determined to be a clock but was not
# created"). Declared as one clock, asynchronous to clk: the cells are
# deliberately untimed (a gate is set one read ahead, the response is sampled
# through a 2-flop synchronizer after SETTLE clocks), so no path between the
# two is analysed.
# (pqse_puf_raw's register pgate[31:0]; no other net starts with "pgate")
if {$PUF eq "bfly" && $TOP eq "pqse_gowin_top"} {
  puts $fh "create_clock -name puf_gate -period 1000 -waveform {0 500} \[get_nets {u_top/u_sys/u_core/u_puf/u_raw/pgate*}\]"
  puts $fh "set_clock_groups -asynchronous -group \[get_clocks {clk}\] -group \[get_clocks {puf_gate}\]"
}
close $fh

# ---- project ----
create_project -name pqse -dir $out -pn $PART -device_version C -force
add_file $src
if {$TOP eq "pqse_gowin_top"} { add_file $sdc }

set_option -top_module            $TOP
# a single module as top (TOP=..., make se-gowin-bisect): its ports are not pins
if {$TOP ne "pqse_gowin_top"} { try_option -disable_io_insertion 1 }
set_option -verilog_std           v2001
set_option -include_path          [file join $root hw se]
set_option -output_base_name      pqse

try_option -global_freq           $FREQ
# every synthesis warning in the log (diagnosis)
try_option -print_all_synthesis_warning 1
# area first: the card design has no speed target beyond its clock
try_option -opt_goal              area
try_option -map_option            $MAP
try_option -rw_check_on_ram       0
try_option -replicate_resources   0
# the board's dual-purpose pins are ordinary I/O
try_option -use_mspi_as_gpio      1
try_option -use_sspi_as_gpio      1
# place & route effort (congested fits)
if {$PLACE ne ""} { try_option -place_option $PLACE }
if {$ROUTE ne ""} { try_option -route_option $ROUTE }

run $STEP
