#!/usr/bin/env python3
"""Pick a few NIST vectors and write them as a C header for the testbenches.

    python3 scripts/make_tb_vectors.py vectors/ML-KEM-768.txt hls/tb_vectors.h [hexdir]

With a third argument, the same vectors are also written as $readmemh files
(one byte per line) into hexdir, for the RTL testbench of the Avalon wrapper
and for the System Console script.

Chosen cases: the first KeyGen, the first Encaps, the first valid Decaps, the
first Decaps with a modified ciphertext (implicit rejection), and the first
encapsulation key / decapsulation key that must be rejected.
"""
import os
import sys


def c_array(name, hexstr):
    b = bytes.fromhex(hexstr)
    rows = []
    for i in range(0, len(b), 16):
        rows.append("   " + ", ".join(f"0x{x:02x}" for x in b[i:i + 16]))
    return f"static const uint8_t {name}[{len(b)}] = {{\n" + ",\n".join(rows) + "\n};\n"


def main():
    src, out = sys.argv[1], sys.argv[2]
    tests = [line.split() for line in open(src) if line.strip()]
    pick = {}
    for t in tests:
        kind = t[0]
        if kind == "keygen" and "keygen" not in pick:
            pick["keygen"] = t
        elif kind == "encaps" and "encaps" not in pick:
            pick["encaps"] = t
        elif kind == "decaps" and ("de_" + t[5]) not in pick:
            pick["de_" + t[5]] = t  # first "valid" and first "rejected" case
        elif kind == "ekcheck" and t[3] == "0" and "ekbad" not in pick:
            pick["ekbad"] = t
        elif kind == "dkcheck" and t[3] == "0" and "dkbad" not in pick:
            pick["dkbad"] = t

    kg, en, ekbad, dkbad = pick["keygen"], pick["encaps"], pick["ekbad"], pick["dkbad"]
    decaps = [pick["de_valid"], pick["de_rejected"]]

    h = []
    h.append(f"/* Generated by scripts/make_tb_vectors.py from {os.path.basename(src)} - do not edit */")
    h.append("#include <stdint.h>")
    h.append(f"#define TB_NUM_DECAPS {len(decaps)}")
    h.append(f"/* KeyGen tcId {kg[1]} */")
    h += [c_array("kg_d", kg[2]), c_array("kg_z", kg[3]), c_array("kg_ek", kg[4]), c_array("kg_dk", kg[5])]
    h.append(f"/* Encaps tcId {en[1]} */")
    h += [c_array("en_ek", en[2]), c_array("en_m", en[3]), c_array("en_c", en[4]), c_array("en_k", en[5])]
    for n, t in enumerate(decaps):
        h.append(f"/* Decaps tcId {t[1]} ({t[5]}) */")
        h += [c_array(f"de{n}_dk", t[2]), c_array(f"de{n}_c", t[3]), c_array(f"de{n}_k", t[4])]
    h.append("static const uint8_t* const de_dk[] = {" + ", ".join(f"de{n}_dk" for n in range(len(decaps))) + "};")
    h.append("static const uint8_t* const de_c[] = {" + ", ".join(f"de{n}_c" for n in range(len(decaps))) + "};")
    h.append("static const uint8_t* const de_k[] = {" + ", ".join(f"de{n}_k" for n in range(len(decaps))) + "};")
    h.append(f"/* Encapsulation key that must fail the modulus check, tcId {ekbad[1]} */")
    h.append(c_array("bad_ek", ekbad[2]))
    h.append(f"/* Decapsulation key that must fail the hash check, tcId {dkbad[1]} */")
    h.append(c_array("bad_dk", dkbad[2]))
    open(out, "w").write("\n".join(h) + "\n")

    if len(sys.argv) > 3:
        hexdir = sys.argv[3]
        os.makedirs(hexdir, exist_ok=True)
        files = {"kg_d": kg[2], "kg_z": kg[3], "kg_ek": kg[4], "kg_dk": kg[5],
                 "en_ek": en[2], "en_m": en[3], "en_c": en[4], "en_k": en[5],
                 "bad_ek": ekbad[2], "bad_dk": dkbad[2]}
        for n, t in enumerate(decaps):
            files[f"de{n}_dk"], files[f"de{n}_c"], files[f"de{n}_k"] = t[2], t[3], t[4]
        for name, hexstr in files.items():
            with open(os.path.join(hexdir, name + ".hex"), "w") as f:
                f.write("\n".join(hexstr[i:i + 2] for i in range(0, len(hexstr), 2)) + "\n")
        print(f"wrote {len(files)} .hex files to {hexdir}")
    print(f"wrote {out}: keygen {kg[1]}, encaps {en[1]}, decaps {[t[1] for t in decaps]}, "
          f"bad ek {ekbad[1]}, bad dk {dkbad[1]}")


if __name__ == "__main__":
    main()
