#!/usr/bin/env python3
"""pqse_sram_lib.py - Liberty stub for the SRAM macros of make se-power
RAM_MACRO=1 (scripts/power/pqse_ram_macro.v).

    python3 scripts/power/pqse_sram_lib.py <out.lib>

One cell per RAM shape, pqse_sram_a<AW>_d<DW>: a simple dual-port RAM with a
registered read (clock to rdata 2 ns), inputs with a 0.5 ns setup / 0.1 ns hold
to the rising clock edge, small pin capacitances, and NO power or area: OpenSTA
then reports the logic around the RAMs only. For a chip, add the SRAM
compiler's datasheet power (per read / write, per MHz) for each macro.
"""
import sys

SHAPES = [(10, 25), (10, 16), (8, 17), (8, 16), (7, 7), (9, 32), (6, 65), (6, 64)]

T_CLK_Q = 2.0      # ns, clock to rdata
T_SETUP = 0.5      # ns
T_HOLD = 0.1       # ns
C_IN = 0.005       # pF
T_OUT = 0.2        # ns, output transition


def setup_hold():
    s = []
    for kind, v in (("setup_rising", T_SETUP), ("hold_rising", T_HOLD)):
        s.append(f"""      timing () {{
        related_pin : "clk";
        timing_type : {kind};
        rise_constraint (scalar) {{ values ("{v}"); }}
        fall_constraint (scalar) {{ values ("{v}"); }}
      }}""")
    return "\n".join(s)


def cell(a, d):
    sh = setup_hold()
    return f"""  cell (pqse_sram_a{a}_d{d}) {{
    area : 0;
    dont_use : true;
    dont_touch : true;
    interface_timing : true;
    pin (clk) {{
      direction : input;
      clock : true;
      capacitance : {C_IN};
    }}
    pin (we) {{
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    pin (re) {{
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (waddr) {{
      bus_type : bus{a};
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (raddr) {{
      bus_type : bus{a};
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (wdata) {{
      bus_type : bus{d};
      direction : input;
      capacitance : {C_IN};
{sh}
    }}
    bus (rdata) {{
      bus_type : bus{d};
      direction : output;
      timing () {{
        related_pin : "clk";
        timing_type : rising_edge;
        timing_sense : non_unate;
        cell_rise (scalar) {{ values ("{T_CLK_Q}"); }}
        cell_fall (scalar) {{ values ("{T_CLK_Q}"); }}
        rise_transition (scalar) {{ values ("{T_OUT}"); }}
        fall_transition (scalar) {{ values ("{T_OUT}"); }}
      }}
    }}
  }}
"""


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    widths = sorted({w for s in SHAPES for w in s})
    types = "".join(f"""  type (bus{w}) {{
    base_type : array;
    data_type : bit;
    bit_width : {w};
    bit_from : {w - 1};
    bit_to : 0;
    downto : true;
  }}
""" for w in widths)
    cells = "".join(cell(a, d) for a, d in SHAPES)
    with open(sys.argv[1], "w") as f:
        f.write(f"""/* generated by scripts/power/pqse_sram_lib.py - SRAM macro stubs, no power */
library (pqse_sram) {{
  delay_model : table_lookup;
  time_unit : "1ns";
  voltage_unit : "1V";
  current_unit : "1mA";
  pulling_resistance_unit : "1kohm";
  leakage_power_unit : "1nW";
  capacitive_load_unit (1, pf);
  nom_process : 1.0;
  nom_voltage : 1.8;
  nom_temperature : 25.0;
  default_cell_leakage_power : 0;
  default_inout_pin_cap : {C_IN};
  default_input_pin_cap : {C_IN};
  default_output_pin_cap : 0;
  default_fanout_load : 1;
  input_threshold_pct_rise : 50;
  input_threshold_pct_fall : 50;
  output_threshold_pct_rise : 50;
  output_threshold_pct_fall : 50;
  slew_lower_threshold_pct_rise : 20;
  slew_lower_threshold_pct_fall : 20;
  slew_upper_threshold_pct_rise : 80;
  slew_upper_threshold_pct_fall : 80;
  slew_derate_from_library : 1.0;
{types}{cells}}}
""")
    print(f"pqse_sram_lib: {len(SHAPES)} macro stubs -> {sys.argv[1]}")


if __name__ == "__main__":
    main()
